package suspicious

var Hidden = []string{
	".env", ".git", ".gitignore", ".htpasswd", ".htaccess", ".idea", ".vscode", ".npmrc",
	".DS_Store", ".dockerfile", ".travis.yml", ".yarn.lock", ".editorconfig", ".bashrc",
	".bash_profile", ".zshrc", ".ssh", ".gitmodules", ".history", ".npm-debug.log",
	".gitattributes", ".dockerignore", ".config", ".env.production", ".env.local",
	".env.development", ".env.staging", ".env.testing", ".gitlab-ci.yml", ".gitconfig",
	".credentials", ".htpasswd", ".heroku.yml", ".rails", ".credentials.yml.enc", ".config/database.yml",
	".gitconfig", ".terraform", ".pylintrc", ".flake8", ".vimrc", ".npmrc", ".bash_profile",
	".bash_history", ".profile", ".zprofile", ".irssi", ".m2", ".gradle", ".clang-format",
	".prettierrc", ".editorconfig", ".python-version", ".ruby-version", ".npm-global", ".npmrc",
	".yarnrc", ".envrc", ".docker-compose.yml", ".env.local", ".env.example", ".travis.yml",
	".github", ".gitmodules", ".clang-tidy", ".terraformrc", ".npm-debug.log", ".DS_Store",
	".gitignore", ".composer.json", ".composer.lock", ".eslintrc.json", ".eslintignore",
	".gitlab-ci.yml", ".npm-debug.log", ".yarn.lock", ".yarnrc", ".husky", ".config.json",
	".prettierignore", ".babelrc", ".eslintcache", ".dockerfile", ".dockerignore", ".vscode",
	".aws", ".kube", ".rails", ".terraform", ".vagrant", ".circleci", ".ci", ".travis.yml",
	".gitmodules", ".env.testing", ".nx.json", ".next", ".nextjs", ".npm", ".yarn", ".public",
	".system", ".archive", ".backup", ".log", ".temp", ".cache", ".vagrant", ".tox", ".ci-configuration",
	".local", ".cache", ".sandbox", ".cargo", ".xcode", ".gradle", ".npm-cache", ".pnp.js",
	".jest", ".nuxt", ".yarn-offline-mirror", ".firebase", ".firebase-debug.log", ".firebase.json",
	".nuxt.config.js", ".babelrc.json", ".npm-shrinkwrap.json", ".vscode-test", ".pyenv",
	".pyc", ".idea", ".phantomjs", ".webpack", ".heroku", ".fastlane", ".apk", ".abp", ".tsconfig.json",
	".railsrc", ".bash_logout", ".zsh_history", ".config/yarn/global", ".pouchdb", ".coverage",
	".rbenv", ".terraform.d", ".vagrantfile", ".ci/test", ".deploy", ".osx", ".webconfig",
	".cloud", ".codeship", ".git-credentials", ".subversion", ".svn", ".maven", ".codecov.yml",
	".lintrc", ".bundle", ".gemfile.lock", ".bower.json", ".buildkite", ".sublime-project",
	".sublime-workspace", ".npm-cache", ".jenkins", ".build", ".test", ".appcache", ".dist",
	".releaserc", ".lerna.json", ".coveralls.yml", ".codemagic.yaml", ".watchmanconfig",
	".goreleaser.yml", ".nyc_output", ".lintstagedrc", ".coveragerc", ".prettier.config.js",
	".ember-cli.js", ".gitlab-ci.yml", ".ci/local", ".deployments", ".drush", ".cloudfront",
	".babelrc", ".storybook", ".eslintignore", ".npm-global", ".bit", ".agile", ".devcontainer",
	".editorconfig", ".buildspec.yml", ".license-checker", ".eslintrc.js", ".fabric", ".boxen",
	".ci-scripts", ".sqlitedb", ".docker-compose.override", ".lerna", ".kubernetes", ".testconfig",
}
