package suspicious

var Keywords = []string{
	"query", "id", "cmd", "input", "search", "sql", "select", "order", "filter", "file", "path", "include", "read", "lang", "template",
	"auth", "token", "key", "session", "cookie", "user", "pass", "redirect", "url", "goto", "next", "host", "dest", "load", "proxy", "remote",
	"download", "backup", "config", "debug", "dev", "test", "account", "database", "admin", "control", "panel", "login", "signup", "register",
	"password", "login", "logout", "user", "role", "permission", "verify", "confirm", "activation", "signup", "user_profile", "change_password",
	"register", "signin", "signout", "api", "endpoint", "secret", "auth", "oauth", "key", "access", "secret", "webhook", "api_key", "apikey", "secret_key",
	"public_key", "private_key", "hash", "signature", "cors", "origin", "callback", "jwt", "jwt_token", "session_id", "csrf", "request", "response",
	"token", "auth_token", "session", "cookie", "user_data", "secure", "ssl", "login_token", "api_token", "refresh_token", "cookie", "state", "security",
	"vulnerable", "debug", "dev", "production", "test", "stage", "staging", "error", "failure", "status", "exception", "fatal", "trace", "stack", "backdoor",
	"shell", "script", "inject", "exploit", "payload", "csrf_token", "xss", "sqli", "command", "request", "response", "accept", "deny", "input", "output",
	"config", "setup", "initialize", "template", "init", "register", "confirm", "verify", "disable", "enable", "secret_key", "firewall", "proxy", "loadbalancer",
	"firestore", "firebase", "supabase", "graphql", "mongodb", "postgres", "mysql", "mongodb", "elastic", "elasticsearch", "redis", "aws", "azure", "gcp", "s3",
	"lambda", "cloudflare", "cloudfront", "bucket", "lambda", "cloud", "backup", "restore", "import", "export", "schema", "cloud_storage", "api_gateway", "queue",
	"kafka", "twilio", "heroku", "pusher", "firebase_auth", "stripe", "webhook", "database_url", "user_endpoint", "webhook_url", "push_token", "api_endpoint",
	"supabase_url", "firebase_config", "firebase_auth_token", "secret_file", "private", "logs", "admin", "debugger", "config_file", "poc", "fuzz", "brute", "bypass",
	"exploit", "exploit_db", "shell_exec", "curl", "wget", "admin", "remote", "panel", "setup", "staging", "uploads", "files", "assets", "scripts", "static",
	"resources", "jwt_secret", "ssl_cert", "key", "pki", "cipher", "client_secret", "certificate", "pem", "hmac", "sym_key", "asymmetric", "encryption", "decrypt",
	"compress", "gzip", "deflate", "base64", "base64url", "hashlib", "hashing", "sha256", "md5", "hmac_sha", "signature", "headers", "digest", "cookies",
	"path_traversal", "file_upload", "injectable", "sql", "xss", "open_redirect", "insecure", "csrf", "privilege_escalation", "unauthorized", "backdoor", "scan",
	"vulnerable", "debugging", "automation", "script", "cron", "path", "flask", "express", "django", "rails", "node", "laravel", "mvc", "aspnet", "spring", "nodejs",
	"exec", "file_include", "file_include", "dast", "rce", "clickjacking", "dirbuster", "ssrf", "xxe", "reflective_xss", "stored_xss", "denial_of_service", "bruteforce",
	"broken_authentication", "captcha", "cloud_storage", "insecure_storage", "insecure_api", "unauthorized_api", "unsecured_token", "caching", "no_cache", "cache_control",
	"robots", "sitemap", "caching", "url_path", "urls", "upload", "dump", "local_file_inclusion", "remote_file_inclusion", "input_validation", "output_encoding",
	"script_injection", "smtp", "smtp_password", "tls", "ssl", "smtp_auth", "service_account", "oauth2", "gcp", "mfa", "social_login", "oauth2.0", "oauth2", "oauth", "api_secret", "admin_panel", "access_key", "developer", "client_secret", "hardcoded", "config_file", "database_backup", "users", "passwords", "credentials", "sensitive_data", "sensitive", "credentials", "password", "secret", "token", "api_key", "api_secret", "access_token", "jwt", "jwt_secret", "jwt_token", "session_token", "session_id",
	"session", "cookie", "cookies", "csrf_token", "xsrf_token", "auth_token", "authorization", "api_token", "refresh_token", "access_token", "secret_key", "private_key",
	"public_key", "private", "public", "secret", "key", "token", "api_key", "api_secret", "access_token", "jwt", "jwt_secret", "jwt_token", "session_token", "session_id",
	"session", "cookie", "cookies", "csrf_token", "xsrf_token", "auth_token", "authorization", "api_token", "refresh_token", "access_token", "secret_key", "private_key",
	"public_key", "private", "public", "secret", "key", "token", "api_key", "api_secret", "access_token", "jwt", "jwt_secret", "jwt_token", "session_token", "session_id",
	"session", "cookie", "cookies", "csrf_token", "xsrf_token", "auth_token", "authorization", "refresh_token", "access_token", "secret_key", "private_key", "public_key",
	"private", "public", "secret", "key", "token", "api_key", "api_secret", "access_token", "jwt", "jwt_secret", "jwt_token", "session_token", "session_id", "session",
}
