package suspicious

var Paths = []string{
	"/admin", "/manager", "/root", "/config", "/setup", "/install", "/database", "/dbadmin", "/dashboard",
	"/panel", "/control", "/login", "/user", "/auth", "/profile", "/settings", "/users", "/adminer", "/cms",
	"/core", "/admin/index", "/admin-area", "/manage", "/cpanel", "/adminpanel", "/admin-console", "/admin-tools",
	"/admincp", "/webmail", "/admin/settings", "/admin/config", "/admin/database", "/admin/install", "/adminpanel.php",
	"/wp-admin", "/wp-content", "/wp-includes", "/wp-login.php", "/wp-json", "/admin.php", "/joomla", "/joomla/admin",
	"/drupal", "/drupal/admin", "/umbraco", "/content", "/sitecore", "/magento", "/magento/admin", "/ecommerce", "/blog",
	"/panel.php", "/shop", "/cart", "/catalog", "/product", "/store", "/checkout",
	"/_next", "/_next/static", "/static", "/public", "/src", "/pages", "/components", "/_app", "/_document", "/api", "/graphql",
	"/next", "/nextjs", "/react", "/vue", "/nuxt", "/nuxtjs", "/react-admin", "/ssr", "/static/js", "/static/css",
	"/assets", "/frontend", "/frontend-assets", "/build", "/dist", "/node_modules", "/package.json", "/webpack", "/babel",
	"/_framework", "/_bin", "/aspnet", "/dotnet", "/dotnet/core", "/wwwroot", "/app_data", "/sitecore", "/content",
	"/app", "/api", "/controllers", "/services", "/database", "/pages", "/appsettings.json", "/web.config", "/admin-console",
	"/asp", "/admin-dash", "/dashboard", "/management", "/admin-portal", "/management-api", "/identity-server", "/auth",
	"/identity", "/tokens", "/sign-in",
	"/rails", "/ruby", "/django", "/flask", "/laravel", "/symfony", "/zend", "/express", "/koa", "/meteor", "/sails",
	"/hapi", "/nestjs", "/ember", "/angular", "/backbone", "/polymer", "/wordpress", "/drupal", "/joomla", "/umbraco",
	"/shopify", "/presta", "/magento", "/plone", "/content-management", "/cms-admin", "/content-api", "/admin-console",
	"/admin/config", "/admin/setup", "/admin/logs", "/admin/database", "/admin/backup", "/debug", "/dev", "/api/v1",
	"/api/v2", "/admin/configuration", "/private", "/hidden", "/secret", "/secure", "/conf", "/files", "/storage",
	"/uploads", "/upload", "/static/uploads", "/backup", "/restore", "/temp", "/tmp", "/public_html", "/db", "/sql", "/scripts",
	"/api/v1/admin", "/cms-admin", "/setup", "/install", "/test", "/staging", "/test-site", "/api-testing", "/debug-mode",
	"/dev-mode", "/maintenance", "/maintenance-mode", "/service-status", "/error", "/logs", "/error-logs", "/admin/maintenance",
	"/admin/backup", "/admin/configuration", "/admin-tools", "/admin-dashboard", "/log", "/logins", "/error", "/error-page",
	"/dev", "/staging", "/test", "/dev-mode", "/testing", "/staging-area", "/debug", "/debug-mode", "/debugger",
	"/ping", "/healthcheck", "/status", "/service", "/status-page", "/test-api", "/demo", "/api-demo", "/test-data",
	"/testing-api", "/test-api-endpoint", "/graphql-test", "/graphql-api", "/api-testing", "/test-data",
	"/.env", "/.git", "/.git/config", "/.gitignore", "/.htpasswd", "/.htaccess", "/.idea", "/.vscode", "/composer.json",
	"/package.json", "/webpack.config.js", "/appsettings.json", "/config.json", "/server.json", "/database.json",
	"/tsconfig.json", "/yarn.lock", "/docker-compose.yml", "/dockerfile", "/readme.md", "/LICENSE", "/npm-debug.log",
	"/error-log", "/sysadmin", "/debug-log", "/logfile", "/backup-config", "/logs/database.log", "/setup.log", "/upload.log",
	"/phpmyadmin", "/mysql", "/adminer", "/pgadmin", "/mongod", "/redis", "/elasticsearch", "/admin-db", "/admin/redis",
	"/phpmyadmin/index.php", "/admin/pgadmin", "/admin/management", "/monitoring", "/supervisor", "/supervisord",
	"/prometheus", "/grafana", "/stats", "/metrics", "/v1", "/v2", "/health-check", "/admin-tools",
	"/api/v1/admin", "/api/v1/management", "/api/v1/config", "/api/v1/healthcheck", "/api/v2/logs", "/graphql/v1",
	"/api/v1/auth", "/api/v1/tokens", "/api/v1/identity", "/api/v1/upload", "/api/v1/download", "/api/v1/files",
	"/api/v1/admin-dashboard", "/api/v1/error", "/api/v2/error",
}
